name: BuildTest(push)
on:
  push:
jobs:
  build-test:
    name: backend test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules(yarn.lock)
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('ttis-back/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ env.cache-name }}
      - name: package-install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: build
        run: yarn build:all
